FROM alpine:3.18@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:51e6d8edd1ed33d328af83d5b99bd5551a034959c71bd81a973f71d21133bc7e

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
